import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,Menu,X,Code2,Layers,Box,ShoppingBag,Sparkles,Mail,Phone,ExternalLink,ChevronDown} from 'lucide-react';
import {motion} from 'framer-motion';
import './style.css';

const projects=[
 {n:'01',title:'House of Aureoné',cat:'Fashion / E-commerce',type:'SHOWCASE TEMPLATE',desc:'A quiet-luxury fashion storefront concept for suits, sarees and fine jewellery, with a streamlined WhatsApp ordering journey.',url:'https://house-of-aureone.vercel.app/',img:'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1600&q=85'},
 {n:'02',title:'Ember & Bean',cat:'Café / Restaurant',type:'SHOWCASE TEMPLATE',desc:'A warm editorial café experience combining premium brand storytelling, menu presentation and a restrained real-time 3D layer.',url:'https://cafe-template-theta.vercel.app/',img:'https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=1600&q=85'},
 {n:'03',title:'Nova Estates',cat:'Real Estate',type:'SHOWCASE TEMPLATE',desc:'A premium property experience built around architecture, listings, investment storytelling and an interactive day/night building scene.',url:'https://real-estate-template-ecru.vercel.app/',img:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=85'},
 {n:'04',title:'FORMA',cat:'Interior Design',type:'SHOWCASE TEMPLATE',desc:'An editorial interior architecture concept focused on materiality, proportion, project storytelling and interactive spatial details.',url:'https://interior-designer-template-navy.vercel.app/',img:'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1600&q=85'},
 {n:'05',title:'Aurelia Grand',cat:'Hospitality',type:'SHOWCASE TEMPLATE',desc:'A cinematic hotel experience showcasing rooms, amenities, dining and immersive 3D spaces for premium hospitality brands.',url:'https://hotel-management-template.vercel.app/',img:'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1600&q=85'}
];
const skills=['React','JavaScript','HTML / CSS','Node.js','MongoDB','REST APIs','Three.js','Framer Motion','Tailwind CSS','Git / GitHub','Vercel','Python','PyTorch','TensorFlow','Playwright'];
function App(){const [open,setOpen]=useState(false); const [scrolled,setScrolled]=useState(false); useEffect(()=>{const f=()=>setScrolled(scrollY>30);addEventListener('scroll',f);return()=>removeEventListener('scroll',f)},[]); return <div className="app">
 <nav className={scrolled?'nav scrolled':'nav'}><a className="logo" href="#home">KT<span>.</span></a><div className={open?'links show':'links'}>{['Work','Services','About','Contact'].map(x=><a key={x} href={'#'+x.toLowerCase()} onClick={()=>setOpen(false)}>{x}</a>)}<a className="navCta" href="#contact">Start a project <ArrowUpRight size={15}/></a></div><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></nav>
 <main id="home">
 <section className="hero"><div className="orb orb1"/><div className="orb orb2"/><div className="eyebrow"><span/> FREELANCE WEB DEVELOPER · INDIA</div><motion.h1 initial={{opacity:0,y:40}} animate={{opacity:1,y:0}} transition={{duration:.8}}>Digital experiences<br/><em>built to stand out.</em></motion.h1><p className="lead">I design and develop modern websites, e-commerce experiences and interactive 3D interfaces for businesses, brands and ambitious ideas.</p><div className="heroBtns"><a className="primary" href="#work">Explore my work <ArrowUpRight/></a><a className="secondary" href="#contact">Let's talk</a></div><div className="scroll">SCROLL TO EXPLORE <ChevronDown size={15}/></div></section>
 <section className="marquee"><div>{['WEB DEVELOPMENT','E-COMMERCE','3D EXPERIENCES','FULL-STACK','AI INTEGRATION','RESPONSIVE DESIGN'].map((x,i)=><span key={i}>{x} <b>✦</b></span>)}</div></section>
 <section id="work" className="section work"><div className="sectionHead"><div><p className="kicker">01 / SELECTED SHOWCASE</p><h2>Work that sells<br/><em>the possibility.</em></h2></div><p className="sectionIntro">A collection of premium website concepts created to demonstrate how I approach different industries. Each template is a showcase concept, ready to be customized for a real business.</p></div><div className="projects">{projects.map((p,i)=><motion.article className="project" key={p.title} initial={{opacity:0,y:35}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-80px'}} transition={{duration:.6,delay:i*.05}}><a href={p.url} target="_blank" rel="noreferrer" className="projectImage"><img src={p.img}/><div className="overlay"><span>VIEW LIVE TEMPLATE <ExternalLink size={16}/></span></div><small>{p.n}</small></a><div className="projectInfo"><div><span className="tag">{p.type}</span><h3>{p.title}</h3><p className="cat">{p.cat}</p></div><p className="desc">{p.desc}</p><a href={p.url} target="_blank" rel="noreferrer" className="round"><ArrowUpRight/></a></div></motion.article>)}</div></section>
 <section id="services" className="section services"><div className="sectionHead"><div><p className="kicker">02 / WHAT I BUILD</p><h2>From idea to<br/><em>live website.</em></h2></div><p className="sectionIntro">I focus on websites that look premium, communicate clearly and are practical to launch, maintain and grow.</p></div><div className="serviceGrid">{[[Code2,'Business Websites','Responsive, conversion-focused websites for brands, startups and local businesses.'],[ShoppingBag,'E-commerce','Product experiences, catalogues, ordering flows and business integrations.'],[Box,'Interactive 3D','Three.js/WebGL experiences, 3D showcases and immersive product or property presentations.'],[Layers,'Full-Stack Development','Frontend, backend, APIs, databases, authentication and admin dashboards.'],[Sparkles,'AI & Automation','AI-powered features, API integrations and workflows that reduce repetitive work.'],[Code2,'Launch & Support','Performance checks, responsive QA, deployment and practical post-launch support.']].map(([Icon,t,d])=><div className="service" key={t}><Icon/><h3>{t}</h3><p>{d}</p><span>↗</span></div>)}</div></section>
 <section className="stack"><div><p className="kicker">03 / THE TOOLKIT</p><h2>A stack chosen<br/>for <em>shipping.</em></h2></div><div className="skillList">{skills.map((s,i)=><span key={i}>{s}</span>)}</div></section>
 <section id="about" className="section about"><div className="aboutGrid"><div><p className="kicker">04 / ABOUT</p><h2>Engineering meets<br/><em>visual craft.</em></h2></div><div className="aboutText"><p>I’m Kartik Thakur, a developer who enjoys turning rough ideas into polished digital products. My work sits at the intersection of frontend engineering, interactive experiences, AI/ML and software quality.</p><p>I care about the details that make a site feel finished: responsive behavior, clear user journeys, performance, reliable interactions and a visual system that makes the brand memorable.</p><div className="facts"><div><strong>Web</strong><span>Modern responsive experiences</span></div><div><strong>3D</strong><span>Interactive digital showcases</span></div><div><strong>AI</strong><span>Practical intelligent features</span></div></div></div></div></section>
 <section className="process"><p className="kicker">05 / PROCESS</p><h2>Simple process.<br/><em>Serious output.</em></h2><div className="steps">{[['01','Discover','Understand the business, audience and goals.'],['02','Design','Shape the structure, visual direction and user journey.'],['03','Develop','Build responsive, interactive and maintainable experiences.'],['04','Launch','Test, optimize, deploy and hand over a production-ready site.']].map(x=><div className="step" key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
 <section id="contact" className="contact"><div className="contactInner"><p className="kicker">06 / HAVE A PROJECT?</p><h2>Let's build something<br/><em>worth remembering.</em></h2><p>Tell me what you're building. I'll help turn the idea into a fast, polished and scalable digital experience.</p><div className="contactBtns"><a href="mailto:kartikthakur2004@gmail.com" className="primary"><Mail/> Email me</a><a href="tel:+919816278345" className="secondary"><Phone/> Call me</a></div><div className="contactInfo"><span>kartikthakur2004@gmail.com</span><span>+91 98162 78345</span><a href="https://github.com/" target="_blank">GitHub ↗</a><a href="https://www.linkedin.com/" target="_blank">LinkedIn ↗</a></div></div></section>
 </main><footer><span>KT.</span><p>© 2026 Kartik Thakur · Freelance Web Developer</p><a href="#home">Back to top ↑</a></footer></div>}
createRoot(document.getElementById('root')).render(<App/>);
